### PR TITLE
Feature/read srv records

### PR DESCRIPTION
**Pull request by MatthiasLohr**
Here is some code for finding LDAP(S) servers with the SRV records. I'm not sure how to integrate this into your code without braking backwards compatibility.

### CODE REVIEW

**Comment by relwell** [comment]
@MatthiasLohr what about this changeset would break backwards compatibility?

**Comment by MatthiasLohr** [comment]
Atm nothing, but i'm not sure how to call it in a clean way in symfony, so i didn't touch your code.

**Comment by relwell** [comment]
Okay, cool. Please try to integrate it more into the bundle and then I'll merge it

**Comment by MatthiasLohr** [comment]
I think i need your help here ;)

**Comment by relwell** [comment]
Ah okay. I'm pretty swamped these days but I'll try to get around to it.

**Pull request merged**
